language: java
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - aleeexr7@gmail.com
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=alejandrorsanchez
    -Dsonar.login=$SONAR

